name: Generate coverage

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.9"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Perform unit tests
        run: |
          coverage run --omit='./tests/*' \
          -m pytest tests/test_machine.py -o log_cli=true -v
      - name: Generate coverage report
        run: coverage lcov
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
          git-branch: main
